#!/usr/bin/env bash

set -eu -o pipefail

: "${PACKAGES=./...}"

gotestsum \
	--format=standard-verbose \
	--packages="$PACKAGES" \
	--jsonfile=/out/testreports/go-test-report.json \
	--junitfile=/out/testreports/junit-report.xml \
	-- -v -mod=vendor -coverprofile=/out/testreports/coverage-report.txt -covermode=atomic "$PACKAGES"
